// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// updateLoopCpp
double updateLoopCpp(const arma::mat S, arma::mat& Q, arma::mat& Qinv, double loglik_s, double lambda, double tol_inner, int max_inner_iter);
RcppExport SEXP _pcglassoFast_updateLoopCpp(SEXP SSEXP, SEXP QSEXP, SEXP QinvSEXP, SEXP loglik_sSEXP, SEXP lambdaSEXP, SEXP tol_innerSEXP, SEXP max_inner_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Qinv(QinvSEXP);
    Rcpp::traits::input_parameter< double >::type loglik_s(loglik_sSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type tol_inner(tol_innerSEXP);
    Rcpp::traits::input_parameter< int >::type max_inner_iter(max_inner_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(updateLoopCpp(S, Q, Qinv, loglik_s, lambda, tol_inner, max_inner_iter));
    return rcpp_result_gen;
END_RCPP
}
// updateBeta
void updateBeta(arma::vec& beta, const arma::mat& Qinv_ii, arma::vec& Qinv_beta, const arma::vec& s, double lambda, int p);
RcppExport SEXP _pcglassoFast_updateBeta(SEXP betaSEXP, SEXP Qinv_iiSEXP, SEXP Qinv_betaSEXP, SEXP sSEXP, SEXP lambdaSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Qinv_ii(Qinv_iiSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Qinv_beta(Qinv_betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    updateBeta(beta, Qinv_ii, Qinv_beta, s, lambda, p);
    return R_NilValue;
END_RCPP
}
// Qinv_down_subet
arma::mat Qinv_down_subet(const arma::mat& Qinv, const arma::mat& qtq, int i);
RcppExport SEXP _pcglassoFast_Qinv_down_subet(SEXP QinvSEXP, SEXP qtqSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Qinv(QinvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type qtq(qtqSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(Qinv_down_subet(Qinv, qtq, i));
    return rcpp_result_gen;
END_RCPP
}
// Qinv_up_cpp
void Qinv_up_cpp(arma::mat& Qinv, const arma::mat& Qinv_ii, const arma::vec& Q_i, int i);
RcppExport SEXP _pcglassoFast_Qinv_up_cpp(SEXP QinvSEXP, SEXP Qinv_iiSEXP, SEXP Q_iSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Qinv(QinvSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Qinv_ii(Qinv_iiSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Q_i(Q_iSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Qinv_up_cpp(Qinv, Qinv_ii, Q_i, i);
    return R_NilValue;
END_RCPP
}
// Qinv_down_cpp
arma::mat Qinv_down_cpp(const arma::mat& Qinv, int i);
RcppExport SEXP _pcglassoFast_Qinv_down_cpp(SEXP QinvSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Qinv(QinvSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(Qinv_down_cpp(Qinv, i));
    return rcpp_result_gen;
END_RCPP
}
