# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateLoopCpp <- function(S, Q, Qinv, loglik_s, lambda, tol_inner, max_inner_iter) {
    .Call(`_pcglassoFast_updateLoopCpp`, S, Q, Qinv, loglik_s, lambda, tol_inner, max_inner_iter)
}

boxQpCpp <- function(Q, u, b, rho, maxIter, tol) {
    .Call(`_pcglassoFast_boxQpCpp`, Q, u, b, rho, maxIter, tol)
}

primalDualSweepCpp <- function(S, R, U, lambda, qpMaxIter, qpTol) {
    .Call(`_pcglassoFast_primalDualSweepCpp`, S, R, U, lambda, qpMaxIter, qpTol)
}

primalDualOuterCpp <- function(S, R, U, lambda, outerMaxIter, outerTol, qpMaxIter, qpTol) {
    .Call(`_pcglassoFast_primalDualOuterCpp`, S, R, U, lambda, outerMaxIter, outerTol, qpMaxIter, qpTol)
}

updateBeta <- function(beta, Qinv_ii, Qinv_beta, s, lambda, p) {
    invisible(.Call(`_pcglassoFast_updateBeta`, beta, Qinv_ii, Qinv_beta, s, lambda, p))
}

Qinv_down_subet <- function(Qinv, qtq, i) {
    .Call(`_pcglassoFast_Qinv_down_subet`, Qinv, qtq, i)
}

Qinv_up_cpp <- function(Qinv, Qinv_ii, Q_i, i) {
    invisible(.Call(`_pcglassoFast_Qinv_up_cpp`, Qinv, Qinv_ii, Q_i, i))
}

Qinv_down_cpp <- function(Qinv, i) {
    .Call(`_pcglassoFast_Qinv_down_cpp`, Qinv, i)
}

